version: '3.8'

services:
  web:
    image: php:7.4-apache
    container_name: lamp_web
    volumes:
      - ./src:/var/www/html/
    ports:
      - "8080:80"
    networks:
      - lampnet
    restart: always

  db:
    image: mysql:5.7
    container_name: lamp_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: your_name_db
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - lampnet
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: your_name_db  # Add this line to use the same database
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - lampnet
    restart: always

volumes:
  db_data:

networks:
  lampnet:

